### ISSUE TITLE
Browsing is too slow

### ISSUE THREAD

**Issue by majk1** [majk1/ldap-browser-idea-plugin#4]
Currently, the browsing is too slow in version `1.4`.

**Comment by gbatalski** [comment]
Probably, we should reduce the amount of children for reading the attributes. Now its limited to 100, so on the large directories up to 1+100 reads are necessary. I think, 5-10 could be enough. On refresh (or even -only?- on editor opening), the attributes could be read for each particular node. Please, check this line:  https://github.com/majk1/ldap-browser-idea-plugin/blob/97a2738b7406fa9c9f15a78ce3377199b5a91a90/src/org/majki/intellij/ldapbrowser/ldap/LdapNode.java#L136

**Comment by gbatalski** [comment]
After updating the ldap library, additional lookup for attributes seems to be unnecessary. Also the limitation to 100 doesn't make sense anymore. But if the repo is realy large, the tree can crash. Some kind pagination should be implemented here. At least, the behaviour isn't worse then it was until 1.4.  Please take a look at the PR #7

**Comment by majk1** [comment]
Thank you @gbatalski , I'll check that tomorrow (or today? :) ), and if it solves the slowness, I'll close this issue too. The apache directory studio is also using pagination, so it is a good idea, however i don't really like the way it is done there.

**Comment by majk1** [comment]
The browsing is a bit faster now, but still too slow to be acceptable after the ldap lib upgrade to the 2.0.0.AM2.
